import { globSync } from "glob";
import { readJson } from "../src/config-generation/config-utils";
import { apiDataSchema } from "../src/types";
import * as fs from "fs";
import { join } from "path";
import prettier from "prettier";


const HEADER_CONTENT = `// ===========================================================================
// DO NOT EDIT THIS FILE MANUALLY!
//
// The contents have been added automatically.
// See: scripts/generate-apis.ts for more information
// ===========================================================================
`;

const GENERATED_FILES_DIR = "./src/generated";
const prettierConfig = readJson("./.prettierrc");

async function generateApiDataJson() {
  
  const apiDataPaths = globSync("./data/apis/*/api-data.json");
  let apiDataJson = {};
  apiDataPaths.forEach((path) => {
    const apiData = apiDataSchema.parse(readJson(path));
    apiDataJson[apiData.alias] = apiData;
  });
  
  if (!fs.existsSync(GENERATED_FILES_DIR)) {
    fs.mkdirSync(GENERATED_FILES_DIR);
  }

  const formattedContent = await prettier.format(`${HEADER_CONTENT}\nexport const apisData = ${JSON.stringify(apiDataJson)}`, { ...prettierConfig, parser: "typescript" });
  fs.writeFileSync(join(GENERATED_FILES_DIR, "apis.ts"), formattedContent);

}


generateApiDataJson();