name: Trigger on Registry Package Publish

on:
  registry_package:
    types: [published]
  pull_request:
    branches: [ main ]
permissions:
    contents: write
jobs:
  Trigger:
    if : github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'manual trigger')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: api3dao/logos
        event-type: release